"""Built-in domain glossaries seeded into the vector DB so the RAG pipeline
understands each domain's definitions, KPIs and formulas out of the box."""

GLOSSARIES: dict[str, list[str]] = {
    "healthcare": [
        "Average Length of Stay (ALOS): total inpatient days divided by number of discharges. A core hospital efficiency KPI; rising ALOS can indicate discharge bottlenecks or higher patient acuity.",
        "Readmission rate: percentage of patients readmitted within 30 days of discharge. High readmission rates suggest premature discharge, poor follow-up care, or care-quality issues, and often carry financial penalties.",
        "Bed occupancy rate: occupied bed-days divided by available bed-days. Above ~85% sustained occupancy is associated with patient-safety risks and ED boarding.",
        "Patient acuity: severity of a patient's condition; higher acuity case mix increases length of stay, staffing needs, and cost per case.",
        "Case Mix Index (CMI): average diagnosis-related group (DRG) weight of all cases; higher CMI means more complex, resource-intensive patients and higher expected reimbursement.",
        "ED throughput: emergency department flow metrics - door-to-doctor time, length of visit, left-without-being-seen (LWBS) rate. Deteriorating throughput often signals capacity or staffing problems.",
        "HCAHPS: standardized patient-satisfaction survey scores affecting reimbursement in value-based programs.",
        "Cost per case: total operating cost attributed to a case; analyzed against reimbursement to find loss-making service lines.",
        "Clinical outcome measures: mortality rate, complication rate, hospital-acquired infection (HAI) rate; risk-adjusted before comparing across units or hospitals.",
        "Payor mix: distribution of revenue across insurance types (government, commercial, self-pay). Shifts in payor mix directly change average reimbursement per case.",
    ],
    "supplychain": [
        "OTIF (On-Time In-Full): percentage of orders delivered on the promised date with complete quantity. The headline delivery-performance KPI; OTIF drops usually trace to stockouts, carrier delays, or forecast misses.",
        "Inventory turnover: cost of goods sold divided by average inventory. Low turnover means excess or obsolete stock tying up working capital; very high turnover risks stockouts.",
        "Days of inventory on hand (DOH/DSI): average inventory divided by daily COGS; how many days current stock will last.",
        "Lead time: elapsed time from order placement to receipt. Longer or more variable supplier lead times force higher safety stock.",
        "Safety stock: buffer inventory held against demand and lead-time variability; typically sized from demand variance and target service level.",
        "Fill rate: fraction of customer demand satisfied from stock immediately. Distinct from OTIF: fill rate is line-level availability, OTIF is full-order delivery performance.",
        "Stockout rate: share of SKU-days (or order lines) with zero available inventory; directly drives lost sales and OTIF failures.",
        "Forecast accuracy / MAPE: mean absolute percentage error between forecast and actual demand; poor accuracy cascades into wrong purchasing and stockouts or overstock.",
        "Perfect order rate: orders delivered on time, in full, damage-free and with correct documentation; the strictest composite delivery KPI.",
        "Supplier performance: on-time delivery rate, quality reject rate (PPM), and price variance per supplier; chronic underperformers drive expediting cost and production stoppage.",
        "Logistics cost per unit: total freight and warehousing cost divided by units shipped; spikes usually trace to expedited shipping, fuel surcharges, or poor load consolidation.",
    ],
    "hr": [
        "Attrition rate (turnover): employees who left divided by average headcount over a period, annualized. Voluntary vs involuntary attrition have different causes; regretted attrition (high performers leaving) is the most damaging.",
        "Retention rate: share of employees present at period start who remain at period end; complement of attrition.",
        "Time to fill: days from job requisition opening to offer acceptance. Long time-to-fill indicates sourcing problems or uncompetitive offers.",
        "Time to productivity (ramp time): time for a new hire to reach expected output; long ramp raises the true cost of attrition.",
        "Cost per hire: total recruiting spend (agency, advertising, recruiter time) divided by hires.",
        "Offer acceptance rate: offers accepted divided by offers extended; low rates point to compensation gaps or slow processes.",
        "eNPS (employee Net Promoter Score): would-recommend score from engagement surveys; leading indicator of attrition.",
        "Absenteeism rate: unscheduled absence days divided by scheduled work days; rising absenteeism often precedes resignations.",
        "Span of control: direct reports per manager; very high spans correlate with lower engagement and higher attrition.",
        "Compa-ratio: employee salary divided by the midpoint of their salary band; compa-ratios well below 1.0 across a team are an attrition risk flag.",
        "Diversity metrics: representation and pay-equity ratios across gender/ethnicity by level; analyzed in hiring funnel and promotion rates.",
    ],
    "retail": [
        "Same-store sales (comparable sales): sales growth from stores open at least a year, isolating organic growth from store openings.",
        "Average transaction value (ATV) / basket size: revenue divided by number of transactions; price and attach-rate initiatives move ATV.",
        "Units per transaction (UPT): average items per basket; cross-sell effectiveness measure.",
        "Conversion rate: transactions divided by store footfall (or site visits online); low conversion with high traffic points to assortment, pricing, or experience problems.",
        "Sell-through rate: units sold divided by units received for a product/season; low sell-through forecasts markdown pressure.",
        "Gross margin return on inventory (GMROI): gross margin dollars divided by average inventory cost; the key buying-efficiency metric.",
        "Shrinkage: inventory loss from theft, damage, or admin error; measured as a percentage of sales.",
        "Markdown rate: discount dollars divided by sales; spikes usually trace to overbuying or late-season inventory.",
        "Customer lifetime value (CLV): projected total margin from a customer; compared against customer acquisition cost (CAC).",
        "Seasonality: recurring demand patterns (holidays, back-to-school); year-over-year comparisons matter more than month-over-month for seasonal categories.",
        "Attach rate: ratio of accessory/add-on sales to primary product sales; a driver of basket size and margin mix.",
    ],
}
